import { chromium } from 'playwright'
const OUT = '/tmp/claude-0/-home-user-frenesi-os/a9f02283-7d3f-50b8-925d-0990ff2bfa56/scratchpad'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const page = await browser.newPage({ viewport: { width: 1440, height: 960 } })
await page.goto('http://localhost:3232/produtos', { waitUntil: 'networkidle' })
console.log('total:', await page.locator('text=/Mostrando \\d+/').textContent())
await page.locator('button:has-text("Baccarat")').first().click()
await page.waitForTimeout(400)
const dialog = page.getByRole('dialog')
console.log('dialog existe:', await dialog.count())
const box = await dialog.boundingBox()
console.log('posicao do dialog:', JSON.stringify(box))
console.log('viewport: 1440x960 — dialog visivel?', box && box.y < 960 && box.y + box.height > 0)
await page.screenshot({ path: `${OUT}/bug-modal-lista-longa.png`, fullPage: false })
await browser.close()
